// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Siscom.Agua.DAL;

namespace Siscom.Agua.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181128153957_TransactionCancel")]
    partial class TransactionCancel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_adress")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgreementsId");

                    b.Property<string>("Indoor")
                        .IsRequired()
                        .HasColumnName("indoor")
                        .HasMaxLength(10);

                    b.Property<string>("Lat")
                        .HasColumnName("lat")
                        .HasMaxLength(20);

                    b.Property<string>("Lon")
                        .HasColumnName("Lon")
                        .HasMaxLength(20);

                    b.Property<string>("Outdoor")
                        .IsRequired()
                        .HasColumnName("outdoor")
                        .HasMaxLength(15);

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnName("reference")
                        .HasMaxLength(200);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnName("street")
                        .HasMaxLength(150);

                    b.Property<int?>("SuburbsId");

                    b.Property<string>("TypeAddress")
                        .HasColumnName("type_address")
                        .HasMaxLength(5);

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnName("zip")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("AgreementsId");

                    b.HasIndex("SuburbsId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Agreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_agreement")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnName("account")
                        .HasMaxLength(50);

                    b.Property<DateTime>("AccountDate")
                        .HasColumnName("account_date");

                    b.Property<int>("Derivatives")
                        .HasColumnName("derivatives");

                    b.Property<int?>("DiameterId");

                    b.Property<DateTime>("StratDate")
                        .HasColumnName("start_date")
                        .HasColumnType("date");

                    b.Property<int?>("TypeCommertialBusinessId");

                    b.Property<int?>("TypeConsumeId");

                    b.Property<int?>("TypeIntakeId");

                    b.Property<int?>("TypePeriodId");

                    b.Property<int?>("TypeRegimeId");

                    b.Property<int?>("TypeServiceId");

                    b.Property<int?>("TypeStateServiceId");

                    b.Property<int?>("TypeUseId");

                    b.HasKey("Id");

                    b.HasIndex("DiameterId");

                    b.HasIndex("TypeCommertialBusinessId");

                    b.HasIndex("TypeConsumeId");

                    b.HasIndex("TypeIntakeId");

                    b.HasIndex("TypePeriodId");

                    b.HasIndex("TypeRegimeId");

                    b.HasIndex("TypeServiceId");

                    b.HasIndex("TypeStateServiceId");

                    b.HasIndex("TypeUseId");

                    b.ToTable("Agreement");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.AgreementDiscount", b =>
                {
                    b.Property<int>("IdDiscount")
                        .HasColumnName("id_discount");

                    b.Property<int>("IdAgreement")
                        .HasColumnName("id_agreement");

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("end_date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("date");

                    b.HasKey("IdDiscount", "IdAgreement");

                    b.HasIndex("IdAgreement");

                    b.ToTable("Agreement_Discount");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.AgreementLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_agreement_log")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgreementId");

                    b.Property<DateTime>("AgreementLogDate")
                        .HasColumnName("agreement_log_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasMaxLength(30);

                    b.Property<string>("Observation")
                        .HasColumnName("observation");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AgreementId");

                    b.HasIndex("UserId");

                    b.ToTable("Agreement_Log");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.AgreementService", b =>
                {
                    b.Property<int>("IdService")
                        .HasColumnName("id_service");

                    b.Property<int>("IdAgreement")
                        .HasColumnName("id_agreement");

                    b.Property<DateTime>("DateAgreement")
                        .HasColumnName("agreement_date");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.HasKey("IdService", "IdAgreement");

                    b.HasIndex("IdAgreement");

                    b.ToTable("Agreement_Service");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.ApplicationRol", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.BranchOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_branch_office")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Closing")
                        .HasColumnName("closing");

                    b.Property<bool>("DontClose")
                        .HasColumnName("dont_close");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(30);

                    b.Property<DateTime>("Opening")
                        .HasColumnName("opening");

                    b.HasKey("Id");

                    b.ToTable("Branch_Office");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Clasification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_clasification")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Clasification");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_client")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgreementId");

                    b.Property<string>("CURP")
                        .HasColumnName("curp")
                        .HasMaxLength(18);

                    b.Property<string>("EMail")
                        .HasColumnName("email")
                        .HasMaxLength(150);

                    b.Property<string>("INE")
                        .HasColumnName("ine")
                        .HasMaxLength(13);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(80);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnName("rfc")
                        .HasMaxLength(13);

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasColumnName("second_last_name")
                        .HasMaxLength(80);

                    b.Property<string>("TypeUser")
                        .HasColumnName("type_user")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("AgreementId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Consumption", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id_consumption");

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnName("consumption_date");

                    b.Property<double>("CurrentConsumption")
                        .HasColumnName("current_consumption");

                    b.Property<int?>("DebtId");

                    b.Property<int?>("MeterId");

                    b.Property<double>("PreviousConsumption")
                        .HasColumnName("previous_consumption");

                    b.Property<double>("consumption")
                        .HasColumnName("consumption");

                    b.Property<bool>("is_active")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.HasIndex("MeterId");

                    b.ToTable("Consumption");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_contact")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<int>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("phone_number")
                        .HasMaxLength(50);

                    b.Property<string>("TypeNumber")
                        .IsRequired()
                        .HasColumnName("type_number");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_control")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnName("alias")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<int?>("ViewId");

                    b.HasKey("Id");

                    b.HasIndex("ViewId");

                    b.ToTable("Control");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_country")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnName("abbreviation")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Debt", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id_debt");

                    b.Property<int?>("AgreementId");

                    b.Property<double>("Amount")
                        .HasColumnName("amount");

                    b.Property<string>("Consumption")
                        .IsRequired()
                        .HasColumnName("consumption")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DebitDate")
                        .HasColumnName("debit_date");

                    b.Property<int?>("DebtPeriodId");

                    b.Property<int>("Derivatives")
                        .HasColumnName("derivatives");

                    b.Property<string>("Discount")
                        .HasColumnName("discount")
                        .HasMaxLength(50);

                    b.Property<DateTime>("FromDate")
                        .HasColumnName("from_date")
                        .HasColumnType("date");

                    b.Property<double>("OnAccount")
                        .HasColumnName("on_account");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("status")
                        .HasMaxLength(5);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasMaxLength(5);

                    b.Property<string>("TypeIntake")
                        .IsRequired()
                        .HasColumnName("type_intake")
                        .HasMaxLength(50);

                    b.Property<string>("TypeService")
                        .IsRequired()
                        .HasColumnName("type_service")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UntilDate")
                        .HasColumnName("until_date")
                        .HasColumnType("date");

                    b.Property<short>("Year")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AgreementId");

                    b.HasIndex("DebtPeriodId");

                    b.ToTable("Debt");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.DebtPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_debt_period")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("end_date")
                        .HasColumnType("date");

                    b.Property<short>("Period")
                        .HasColumnName("period");

                    b.Property<DateTime>("RunDate")
                        .HasColumnName("run_date")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("RunHour")
                        .HasColumnName("run_hour")
                        .HasColumnType("time");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("date");

                    b.Property<int?>("TypePeriodId");

                    b.HasKey("Id");

                    b.HasIndex("TypePeriodId");

                    b.ToTable("Debt_Period");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Derivative", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id_derivative");

                    b.Property<int>("AgreementDerivative");

                    b.Property<int?>("AgreementId");

                    b.Property<bool>("is_active")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("AgreementId");

                    b.ToTable("Derivative");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Diameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_diameter")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Diameter");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id_discount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<short>("Percentpercentage")
                        .HasColumnName("percentpercentage");

                    b.Property<int?>("ValidityId");

                    b.Property<bool>("is_active")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("ValidityId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.ExternalOriginPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_external_origin_payment")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("External_Origin_Payment");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Folio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_folio")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchOfficeId");

                    b.Property<DateTime>("DateCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("date_current")
                        .HasDefaultValue(new DateTime(2018, 11, 28, 9, 39, 56, 902, DateTimeKind.Local));

                    b.Property<int>("Initial")
                        .HasColumnName("initial");

                    b.Property<int>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnName("range");

                    b.Property<int>("Secuential")
                        .HasColumnName("secuential");

                    b.HasKey("Id");

                    b.HasIndex("BranchOfficeId");

                    b.ToTable("Folio");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.GroupStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_group_type")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Group_Status");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.GroupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_group_type")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Group_Type");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Meter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id_meter");

                    b.Property<int?>("AgreementId");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnName("brand")
                        .HasMaxLength(50);

                    b.Property<string>("Consumption")
                        .HasColumnName("consumption")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DeinstallDate")
                        .HasColumnName("deinstall_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnName("install_date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasMaxLength(50);

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnName("serial")
                        .HasMaxLength(20);

                    b.Property<string>("Wheels")
                        .IsRequired()
                        .HasColumnName("wheels")
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.HasIndex("AgreementId");

                    b.ToTable("Meter");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.OriginPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_origin_payment")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Origin_Payment");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_payment")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Authorization")
                        .HasColumnName("authorization")
                        .HasMaxLength(50);

                    b.Property<string>("BranchOffice")
                        .IsRequired()
                        .HasColumnName("branch_office")
                        .HasMaxLength(20);

                    b.Property<int>("Debt")
                        .HasColumnName("debt");

                    b.Property<int?>("OriginPaymentId");

                    b.Property<int?>("PayMethodId");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnName("payment_date");

                    b.Property<string>("PercentageTax")
                        .HasColumnName("percentage_tax")
                        .HasMaxLength(2);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("status")
                        .HasMaxLength(5);

                    b.Property<double>("Subtotal")
                        .HasColumnName("subtotal");

                    b.Property<double>("Tax")
                        .HasColumnName("tax");

                    b.Property<double>("Total")
                        .HasColumnName("total");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("OriginPaymentId");

                    b.HasIndex("PayMethodId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.PayMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_pay_method")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Pay_Method");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_region")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_service")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HaveTax")
                        .HasColumnName("have_tax");

                    b.Property<bool>("InAgreement")
                        .HasColumnName("in_agreement");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsService")
                        .HasColumnName("is_service");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<short>("Order")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_state")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountriesId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("CountriesId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Status", b =>
                {
                    b.Property<string>("CodeName")
                        .HasColumnName("id_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasMaxLength(30);

                    b.Property<int?>("GroupStatusId");

                    b.HasKey("CodeName");

                    b.HasIndex("GroupStatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Suburb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_suburb")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClasificationsId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(100);

                    b.Property<int?>("RegionsId");

                    b.Property<int?>("TownsId");

                    b.HasKey("Id");

                    b.HasIndex("ClasificationsId");

                    b.HasIndex("RegionsId");

                    b.HasIndex("TownsId");

                    b.ToTable("Suburb");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_system_log")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnName("action");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnName("controller");

                    b.Property<DateTime>("DateLog")
                        .HasColumnName("date_log");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnName("parameter");

                    b.HasKey("Id");

                    b.ToTable("System_Log");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_tariff")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnName("account_number")
                        .HasMaxLength(20);

                    b.Property<double>("Amount")
                        .HasColumnName("amount");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnName("concept")
                        .HasMaxLength(80);

                    b.Property<DateTime>("FromDate")
                        .HasColumnName("from_date")
                        .HasColumnType("date");

                    b.Property<bool>("HaveTax")
                        .HasColumnName("have_tax");

                    b.Property<int>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<short>("Percentage")
                        .HasColumnName("percentage");

                    b.Property<int?>("ServiceId");

                    b.Property<int?>("TypeIntakeId");

                    b.Property<int?>("TypeServiceId");

                    b.Property<int?>("TypeUseId");

                    b.Property<DateTime>("UntilDate")
                        .HasColumnName("until_date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TypeIntakeId");

                    b.HasIndex("TypeServiceId");

                    b.HasIndex("TypeUseId");

                    b.ToTable("Tariff");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_terminal")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchOfficeId");

                    b.Property<decimal>("CashBox")
                        .HasColumnName("cash_box");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_active")
                        .HasDefaultValue(true);

                    b.Property<string>("MacAdress")
                        .IsRequired()
                        .HasColumnName("mac_adress")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("BranchOfficeId");

                    b.ToTable("Terminal");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TerminalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_terminal_user")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("InOperation")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("in_operation")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("OpenDate")
                        .HasColumnName("open_date")
                        .HasColumnType("date");

                    b.Property<int?>("TerminalId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.HasIndex("UserId");

                    b.ToTable("Terminal_User");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_town")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(30);

                    b.Property<int?>("StatesId");

                    b.HasKey("Id");

                    b.HasIndex("StatesId");

                    b.ToTable("Town");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_transaction")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnName("amount");

                    b.Property<string>("Aplication")
                        .IsRequired()
                        .HasColumnName("aplication")
                        .HasMaxLength(20);

                    b.Property<string>("CancellationFolio")
                        .IsRequired()
                        .HasColumnName("cancellation_folio")
                        .HasMaxLength(40);

                    b.Property<DateTime>("DateTransaction")
                        .HasColumnName("date_transaction");

                    b.Property<string>("Folio")
                        .HasColumnName("folio")
                        .HasMaxLength(40);

                    b.Property<int?>("PayMethodId");

                    b.Property<bool>("Sign")
                        .HasColumnName("sign");

                    b.Property<int?>("TerminalUserId");

                    b.Property<int?>("TypeTransactionId");

                    b.HasKey("Id");

                    b.HasIndex("PayMethodId");

                    b.HasIndex("TerminalUserId");

                    b.HasIndex("TypeTransactionId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TransactionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_transaction_detail")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeConcept")
                        .HasColumnName("code_concept")
                        .HasMaxLength(10);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasMaxLength(30);

                    b.Property<int?>("TransactionId");

                    b.Property<double>("amount")
                        .HasColumnName("amount");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Transaction_Detail");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TransactionFolio", b =>
                {
                    b.Property<string>("Folio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("folio");

                    b.Property<DateTime>("DatePrint");

                    b.Property<int?>("TransactionId");

                    b.HasKey("Folio");

                    b.HasIndex("TransactionId");

                    b.ToTable("Transaction_Folio");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Type", b =>
                {
                    b.Property<string>("CodeName")
                        .HasColumnName("id_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasMaxLength(30);

                    b.Property<int?>("GroupTypeId");

                    b.HasKey("CodeName");

                    b.HasIndex("GroupTypeId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypeCommercialBusiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_commertial_business")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClasificationGroup")
                        .HasColumnName("clasification_group");

                    b.Property<string>("IntakeAcronym")
                        .IsRequired()
                        .HasColumnName("intake_acronym")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Type_Commertial_Business");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypeConsume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_consume")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Type_Consume");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypeIntake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_intake")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnName("acronym")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Type_Intake");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_period")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Mounth")
                        .HasColumnName("mounth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Type_Period");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypeRegime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_regime")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntakeAcronym")
                        .IsRequired()
                        .HasColumnName("intake_acronym")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Type_Regime");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_service")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Type_Service");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypeStateService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_state_service")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Type_State_Service");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_transaction")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Type_Transaction");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TypeUse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_type_use")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntakeAcronym")
                        .IsRequired()
                        .HasColumnName("intake_acronym")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Type_Use");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.View", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_view")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnName("alias")
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("View");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.ViewProfile", b =>
                {
                    b.Property<int>("ViewId")
                        .HasColumnName("id_profile");

                    b.Property<string>("RoleId")
                        .HasColumnName("id_view");

                    b.HasKey("ViewId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("View_Profile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationRol")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationRol")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Adress", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Agreement", "Agreements")
                        .WithMany("Addresses")
                        .HasForeignKey("AgreementsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Siscom.Agua.DAL.Models.Suburb", "Suburbs")
                        .WithMany()
                        .HasForeignKey("SuburbsId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Agreement", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Diameter", "Diameter")
                        .WithMany()
                        .HasForeignKey("DiameterId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeCommercialBusiness", "TypeCommertialBusiness")
                        .WithMany()
                        .HasForeignKey("TypeCommertialBusinessId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeConsume", "TypeConsume")
                        .WithMany()
                        .HasForeignKey("TypeConsumeId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeIntake", "TypeIntake")
                        .WithMany()
                        .HasForeignKey("TypeIntakeId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypePeriod", "TypePeriod")
                        .WithMany()
                        .HasForeignKey("TypePeriodId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeRegime", "TypeRegime")
                        .WithMany()
                        .HasForeignKey("TypeRegimeId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeService", "TypeService")
                        .WithMany()
                        .HasForeignKey("TypeServiceId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeStateService", "TypeStateService")
                        .WithMany()
                        .HasForeignKey("TypeStateServiceId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeUse", "TypeUse")
                        .WithMany()
                        .HasForeignKey("TypeUseId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.AgreementDiscount", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Agreement", "Agreement")
                        .WithMany("AgreementDiscounts")
                        .HasForeignKey("IdAgreement")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Siscom.Agua.DAL.Models.Discount", "Discount")
                        .WithMany("AgreementDiscounts")
                        .HasForeignKey("IdDiscount")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.AgreementLog", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Agreement", "Agreement")
                        .WithMany()
                        .HasForeignKey("AgreementId");

                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.AgreementService", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Agreement", "Agreement")
                        .WithMany("AgreementServices")
                        .HasForeignKey("IdAgreement")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Siscom.Agua.DAL.Models.Service", "Service")
                        .WithMany("AgreementServices")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Client", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Agreement", "Agreement")
                        .WithMany("Clients")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Consumption", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Debt", "Debt")
                        .WithMany()
                        .HasForeignKey("DebtId");

                    b.HasOne("Siscom.Agua.DAL.Models.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Contact", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Control", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.View")
                        .WithMany("Controls")
                        .HasForeignKey("ViewId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Debt", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Agreement", "Agreement")
                        .WithMany()
                        .HasForeignKey("AgreementId");

                    b.HasOne("Siscom.Agua.DAL.Models.DebtPeriod", "DebtPeriod")
                        .WithMany()
                        .HasForeignKey("DebtPeriodId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.DebtPeriod", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.TypePeriod", "TypePeriod")
                        .WithMany()
                        .HasForeignKey("TypePeriodId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Derivative", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Agreement", "Agreement")
                        .WithMany()
                        .HasForeignKey("AgreementId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Discount", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.TypePeriod", "Validity")
                        .WithMany()
                        .HasForeignKey("ValidityId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Folio", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.BranchOffice", "BranchOffice")
                        .WithMany()
                        .HasForeignKey("BranchOfficeId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Meter", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Agreement", "Agreement")
                        .WithMany()
                        .HasForeignKey("AgreementId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Payment", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.OriginPayment", "OriginPayment")
                        .WithMany()
                        .HasForeignKey("OriginPaymentId");

                    b.HasOne("Siscom.Agua.DAL.Models.PayMethod", "PayMethod")
                        .WithMany()
                        .HasForeignKey("PayMethodId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.State", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Country", "Countries")
                        .WithMany("states")
                        .HasForeignKey("CountriesId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Status", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.GroupStatus", "GroupStatus")
                        .WithMany()
                        .HasForeignKey("GroupStatusId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Suburb", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Clasification", "Clasifications")
                        .WithMany()
                        .HasForeignKey("ClasificationsId");

                    b.HasOne("Siscom.Agua.DAL.Models.Region", "Regions")
                        .WithMany()
                        .HasForeignKey("RegionsId");

                    b.HasOne("Siscom.Agua.DAL.Models.Town", "Towns")
                        .WithMany("Suburbs")
                        .HasForeignKey("TownsId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Tariff", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeIntake", "TypeIntake")
                        .WithMany()
                        .HasForeignKey("TypeIntakeId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeService", "TypeService")
                        .WithMany()
                        .HasForeignKey("TypeServiceId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeUse", "TypeUse")
                        .WithMany()
                        .HasForeignKey("TypeUseId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Terminal", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.BranchOffice", "BranchOffice")
                        .WithMany()
                        .HasForeignKey("BranchOfficeId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TerminalUser", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Terminal", "Terminal")
                        .WithMany("TerminalUsers")
                        .HasForeignKey("TerminalId");

                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationUser", "User")
                        .WithMany("TerminalUsers")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Town", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.State", "States")
                        .WithMany("Towns")
                        .HasForeignKey("StatesId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Transaction", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.PayMethod", "PayMethod")
                        .WithMany()
                        .HasForeignKey("PayMethodId");

                    b.HasOne("Siscom.Agua.DAL.Models.TerminalUser", "TerminalUser")
                        .WithMany()
                        .HasForeignKey("TerminalUserId");

                    b.HasOne("Siscom.Agua.DAL.Models.TypeTransaction", "TypeTransaction")
                        .WithMany()
                        .HasForeignKey("TypeTransactionId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TransactionDetail", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.TransactionFolio", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.Transaction", "Transaction")
                        .WithMany("TransactionFolios")
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.Type", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.GroupType", "GroupType")
                        .WithMany()
                        .HasForeignKey("GroupTypeId");
                });

            modelBuilder.Entity("Siscom.Agua.DAL.Models.ViewProfile", b =>
                {
                    b.HasOne("Siscom.Agua.DAL.Models.ApplicationRol", "ApplicationRol")
                        .WithMany("ViewProfiles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Siscom.Agua.DAL.Models.View", "View")
                        .WithMany("ViewProfiles")
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
